dist: xenial
language: node_js
node_js:
    - 10
cache: yarn
after_script:
    - bash <(curl -s https://codecov.io/bash)
deploy:
    provider: npm
    email: hoishinxii@gmail.com
    api_key:
        secure: BYSBAkaTVyKICKZ8p1deRU9EeTuJblUf5bGxTOxazLin4XSew82STIaVBVtfkOdtj5UDa6IjWNyltHhBmcCkWgXyN9TQWVyUzW202bEf7n7pb7fVmZhXsVCADoDkJClCmKFG2zzS8SUOwmlzsZTnqZGc1+pvsFX8xBkhdPLby0wHfZjik9wzstUTqArJZu1hq6tfCBAb7+5rOgw/7nUE8Z6zznifPzHr5l4VvZLKm14jQF41qJfaYk14fUUPUJyJu181VaqEWrxVpm3vegtqCosSkIVDImHqHpVMK4GVgbo0JBzMjP5if620GYVtk74JKL1M0gCkNB4N1coTMz/WO2kbiOsm4G7SIgRwQNK3Ai/n6inT7GInVWfUyf1/Yh3OyqsGPmbmvDAR9qA+XH2vnfs+CDgLW36uxvHuIaBFANRV4ao0BIZ6B7gHlk1j/aaLfhCbauo8zxZrfnkv7OXY1FSAIGTVm7f0qtsh7XM2FXUY/xfFa/ALvfLvy2YX4Xcj0OljmI6HwhMyqqFzmyXrtc1OTuJr8WsOq0jhuc9slXfZvNQc7SI35uIrEAUM7WF4e2dhDLPjq5RRG64MffDMZZtIRiaYP70BOY/Ljspac47s4fxq7OEwsyVUja1oeH1Vhaf0fmEnlt2+kLd4L/LwZieOK+lemJ6A8t7GpMKk1V4=
    tag: next
    on:
        tags: true
        repo: Hoishin/use-nodecg
        branch: master
notifications:
    slack:
        secure: jmYODZvA+mhYExmN3xJRuoljZRE5rypgCpMSbcba7zUfSwRcsbL4fZa69K3BNyXJ67k0tswQQNzbVGpHp86YhxqajLVLjbKIb9bOgymB71TXqAv9Y2IImffLNU+OJHGEa1xsA4vqfp2KNjKIOEDpsFyDuPgtk01kL0aeKcmH9mG4znH1t5ByA3h3zyvshhDP9MKTMN3+dchx5Bwx8429/e9UW6S1VPVgIgKTv2xTOKuxNOfxMPweP/KANpRTDeOtatkdwyvSXBMFJfqHhLN2JZFFebjWMN4CHEd2wGTVgJTmZTT5n8KOA6v+0Nh6agMj5dencgOPyINJ0ESaVUSsU2XWCGgw+c1oL/AHvDMF/6G4yXPNk5O7aR6I+MzWibMYUMbgVhrw+TOkUTfvzqOuQUTPqhl/eaA7nWx58wDKDmh2Z1hX/c1yjc8DQjkHGpijf1Ox97/iOxVXvjZVd2O+CTGLlQchWF6akPfzWRDCKIlMZb2Fo5BaBcKlabloVA4S37GZwHNN0xmOwITBSj7IQtT8nY/0Trgqr9UpmANO6rBAkm0/gua+6Bnt10mbPmJZj9/CfGCYdhHYXVQm+KHI2Ak9gFzFmXmbUZ1bZ1t2IU86qmCAuZHTM/gYAAoWZ1sUMYdI+vpKgDxTr/sd1Uf2CO0BRBj5FEI4qfb0k9nptYU=
