dist: xenial
language: node_js
node_js:
    - 10
cache:
    yarn: true
script:
    - yarn build
deploy:
    provider: npm
    email: hoishinxii@gmail.com
    api_key:
        secure: BYSBAkaTVyKICKZ8p1deRU9EeTuJblUf5bGxTOxazLin4XSew82STIaVBVtfkOdtj5UDa6IjWNyltHhBmcCkWgXyN9TQWVyUzW202bEf7n7pb7fVmZhXsVCADoDkJClCmKFG2zzS8SUOwmlzsZTnqZGc1+pvsFX8xBkhdPLby0wHfZjik9wzstUTqArJZu1hq6tfCBAb7+5rOgw/7nUE8Z6zznifPzHr5l4VvZLKm14jQF41qJfaYk14fUUPUJyJu181VaqEWrxVpm3vegtqCosSkIVDImHqHpVMK4GVgbo0JBzMjP5if620GYVtk74JKL1M0gCkNB4N1coTMz/WO2kbiOsm4G7SIgRwQNK3Ai/n6inT7GInVWfUyf1/Yh3OyqsGPmbmvDAR9qA+XH2vnfs+CDgLW36uxvHuIaBFANRV4ao0BIZ6B7gHlk1j/aaLfhCbauo8zxZrfnkv7OXY1FSAIGTVm7f0qtsh7XM2FXUY/xfFa/ALvfLvy2YX4Xcj0OljmI6HwhMyqqFzmyXrtc1OTuJr8WsOq0jhuc9slXfZvNQc7SI35uIrEAUM7WF4e2dhDLPjq5RRG64MffDMZZtIRiaYP70BOY/Ljspac47s4fxq7OEwsyVUja1oeH1Vhaf0fmEnlt2+kLd4L/LwZieOK+lemJ6A8t7GpMKk1V4=
    tag: next
    on:
        tags: true
        repo: Hoishin/use-nodecg
        branch: master
notifications:
    slack:
        rooms:
            secure: hkTJgltZ+PDwI+Ga3KWiJDI9bZXpIxSxr7gsmzokUwvgzej/7AEOxBAmz+CyE7lHxzwiKVatOCcdtfAJW5rdqwuM2t0/8H4iz3GCpIZO362zCEdO8k6dv/181lU0EMDu56sJmk2ItU3MU9QRLMVCXyP10BT2OSg/hKL2kcBSKy6MIidbKfHy1d66yAj1gP0wwfTuEAcal/oF0qH0ZbeUyn5olr4WPfhGVb8xT+fyD2KYRWeR+PFGtCmkFZ6YQ6dwvL0oYq0DP01JSLgJ5rIiNWIAfq/N9ZTpGrTwgVOrwLLcO3rQOMGlKxJlpsrvI3eMH7WIoXQOEaYGT0Ldat9Mq7RJBrPZxyCATIyXWpQnj1xaa+pZvRtyXq4d6IAlZIUPnT2eWWu88bLQzATABRQKxo5/SUJtSpsF2YDyn7TX3pTUWxDV32zj91IbLf1ArBxYvaBAXE/ECLQqhs73EOha/7XKszG+rVaOKGJnXLeCvYX4as59uRCpOPQe+PJgpZYwGNXH/aGzcKWs/AOP2gj5wEOoWMNPnYtg5Un6kXmN845YLiy2c5spV+kEfW/1fUcQOoA0lqPTF6L3Spfjkyl5U70x/6yZ2Z+IxzZWgOznyJsPaNNtyoNS4oU/MciG7af6Rd4rk0rZpnb6IwjGvcIDgXJDbNhweQBn97LJ/+LW1Wo=
